remote_theme: pages-themes/architect@v0.2.0
title: [Kacper Rabczewski]
description: [Jestem studentem ISIS AGH. Kiedyś zajmnowałem się projektami webowymi np. ObserwujKażdeOgłoszenie.pl - tracker ogłoszeń z OLX]
